### ISSUE TITLE
Separate event pages

### ISSUE THREAD

**Issue by rodrigodiez** [phplondon/phplondon.github.io#1]
## Summary

We could improve the current site by start defining separate pages for each event, using Jekyll YAML features (defining data of events)
### Event URL

http://phplondon.org/events/docker-the-only-thing-it-cant-contain-is-your-exicement
### Event YAML data

``` yaml
title: "Docker: The only thing it can't contain is your excitement"
speaker: 'John Le Drew'
date: 'May 1st 2014'
meetup: 'http://www.meetup.com/phplondon/events/142529142/'
categories:
    - events
    - upcoming
```
## Benefit
- Shareable URL per event. Visibility. 
- Collect potential useful event data (meetup link, map, photos, videos, slides...)
- Easy to implement comments (ie: disqus)
- Easy to maintain upcoming event index (i.e simply list on homepage `upcoming`  + `events` categorized posts)

What do you think?
